# Generated by Django 5.2.1 on 2025-05-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Optional deadline for the task', null=True),
        ),
    ]
